site_name: BunnyChen's Docs
site_description: A description of my docs site
site_author: BunnyChen
site_url: https://bunnychen.github.io/
# Copyright
copyright: Copyright &copy; 2024 Lizhenghe-Chen
repo_url: https://github.com/Lizhenghe-Chen
repo_name: Lizhenghe-Chen
theme:
  name: material
  custom_dir: ./overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  #remove the footer copyright
  generator: false
