site_name: Bunny Chen
site_author: Lizhenghe Chen
site_description: Lizhenghe Chen's personal Blog and Docs

# Copyright
copyright: <a href="/about/LICENSE">Copyright &copy; 2019 - 2025 Lizhenghe Chen | v1.1.2.1</a>
site_url: https://bunnychen.top/
# repo_url: https://bunnychen.top/
# repo_name: BunnyChen

theme:
  language: zh
  logo: assets/images/Avatar.png
  favicon: assets/images/Avatar.png
  name: material
  font: false
  icon:
    repo: material/home
  custom_dir: overrides
  features:
    # - announce.dismiss
    # - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation
    - navigation.footer
    - navigation.indexes
    # currently conflicts with the home page scroll effect
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress

    - navigation.tabs
    - navigation.path
    # - navigation.sections #
    # - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    # switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    # switch to system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/no-copy.js
plugins:
  - blog
  - search:
      # separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
  # - git-revision-date-localized:
  #     enable_creation_date: false
  #     type: datetime

extra:
  #remove the footer copyright
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lizhenghe-Chen
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lizhenghe-chen/
      name: LinkedIn
    - icon: material/file-document-edit
      link: https://blog.csdn.net/weixin_46146935
      name: CSDN

# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
markdown_extensions:
  - abbr
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=permanent#table-of-contents
  - toc:
      toc_depth: 4
      permalink: ヾ(•ω•`)o
      permalink_title: Title link
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - admonition
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
# Page tree
nav:
  - index.md
  - About:
      - about/index.md
      - about/LICENSE.md
      - about/MetaverseJointInnovationLaboratory/index.md
  - Blog:
      - blog/index.md
  # use the file name as the title
  - Docs:
      - docs/index.md
      - UnityDocs:
          - docs/Unity/index.md
          - docs/Unity/BestUnityPluginCollections.md
      - MetaHuman:
          - docs/GPTRelated/index.md
          - docs/GPTRelated/Agent.md
          - docs/GPTRelated/LocalLLM.md
          - Sherpa ASR STT模块:
              - docs/GPTRelated/Sherpa Onnx ASR STT实战.md
              - docs/GPTRelated/Sherpa-onnx STT Windows.md
      - MkDocs Material:
          - docs/mkdocsTutorials/index.md
          - docs/mkdocsTutorials/start.md
          - docs/mkdocsTutorials/MkDocsNote.md
      - Linux Study:
          - docs/Linux/index.md
          - docs/Linux/WSL.md
          - docs/Linux/installUbuntu.md
          - docs/Linux/condaPython.md

