site_name: Bunny Chen's Docs
site_author: Bunny Chen
site_description: Bunny Chen's personal Blog and Docs

# Copyright
copyright: Copyright &copy; 2024 Lizhenghe-Chen
# Page tree
nav:
  - Home: index.md
  - About: about.md
  - blog: blog/index.md
  # use the file name as the title
  - GPTDocs:
      - GPTRelated/Sherpa-onnx 语音转文字.md
      - GPTRelated/UnityGPTChat.md
  - MkDocsNote.md
theme:
  logo: /assets/images/Avatar.png
  favicon: /assets/images/Avatar.png
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    # switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    # switch to system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
plugins:
  - blog:
      blog_dir: blog
      blog_toc: true # 设置blog索引页面的目录
      post_date_format: full # 设置blog索引页面的日期格式
      archive_toc: true
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last" # 设置blog索引页面的分页格式
      pagination_keep_content: true # 设置blog索引页面的分页内容
      draft_if_future_date: true # 设置如果blog的日期是未来的话，就会被当成草稿不会被发布
  - search:

extra:
  #remove the footer copyright
  generator: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - attr_list
